package com.gu.notifications.workerlambda.delivery.fcm.models.payload

object Keys {
  final val Type = "type"
  final val NotificationType = "notificationType"
  final val Debug = "debug"
  final val Title = "title"
  final val Message = "message"
  final val Ticker = "ticker"
  final val Section = "section"
  final val Keyword = "keyword"
  final val Link = "link"
  final val ThumbnailUrl = "thumbnailUrl"
  final val ImageUrl = "imageUrl"
  final val Edition = "edition"
  final val Editions = "editions"
  final val MapiUrl = "mapiUrl"
  final val Uri = "uri"
  final val UriType = "uriType"
  final val Topics = "topics"
  final val UniqueIdentifier = "uniqueIdentifier"
  final val Importance = "importance"
  final val Provider = "provider"
  final val MatchId = "matchId"
  final val HomeTeamName = "homeTeamName"
  final val HomeTeamId = "homeTeamId"
  final val HomeTeamScore = "homeTeamScore"
  final val HomeTeamText = "homeTeamText"
  final val AwayTeamName = "awayTeamName"
  final val AwayTeamId = "awayTeamId"
  final val AwayTeamScore = "awayTeamScore"
  final val AwayTeamText = "awayTeamText"
  final val CurrentMinute = "currentMinute"
  final val MatchStatus = "matchStatus"
  final val MatchInfoUri = "matchInfoUri"
  final val CompetitionName = "competitionName"
  final val Venue = "venue"
  final val ArticleUri = "articleUri"

  final val EditionsDate = "date"
  final val EditionsKey = "key"
  final val EditionsName = "name"

  final val UsElection2020 = "usElection2020"
  final val ExpandedTitle = "expandedTitle"
  final val LeftCandidateName = "leftCandidateName"
  final val LeftCandidateColour = "leftCandidateColour"
  final val LeftCandidateColourDark = "leftCandidateColourDark"
  final val LeftCandidateDelegates = "leftCandidateDelegates"
  final val LeftCandidateVoteShare = "leftCandidateVoteShare"
  final val RightCandidateName = "rightCandidateName"
  final val RightCandidateColour = "rightCandidateColour"
  final val RightCandidateColourDark = "rightCandidateColourDark"
  final val RightCandidateDelegates = "rightCandidateDelegates"
  final val RightCandidateVoteShare = "rightCandidateVoteShare"
  final val TotalDelegates = "totalDelegates"
  final val DelegatesToWin = "delegatesToWin"
  final val ExpandedMessage = "expandedMessage"
  final val Button1Text = "button1Text"
  final val Button1Url = "button1Url"
  final val Button2Text = "button2Text"
  final val Button2Url = "button2Url"
  final val StopButtonText = "stopButtonText"
}



