AWSTemplateFormatVersion: '2010-09-09'
Description: backs up notification azure hubs
Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: mobile-notifications
  App:
    Description: Application Name
    Type: String
    Default: backup
  Stage:
    Description: Stage Name
    Type: String
    AllowedValues:
      - CODE
      - PROD
  DeployBucket:
    Description: S3 Bucket where RiffRaff uploads artifacts on Deploy
    Type: String
    Default: mobile-notifications-dist
  ConfigurationBucket:
    Description: S3 Bucket where the app configuration is hosted
    Type: String
    Default: mobile-notifications-dist
  ConfigurationFileName:
    Description: Name of the file containing the application configuration
    Type: String
    Default: mobile-notifications.properties
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
        - PolicyName: invoke-lambda
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"
        - PolicyName: iam-read-and-assume
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - iam:PassRole
                - iam:GenerateCredentialReport
                - iam:Get*
                - iam:List*
              Resource: "*"
        - PolicyName: s3Config
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub arn:aws:s3:::mobile-notifications-dist/${Stage}/*


  BackupLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Stack}-${App}-${Stage}
      Code:
        S3Bucket: !Ref DeployBucket
        S3Key: !Sub ${Stack}/${Stage}/${App}/${App}.jar
      Environment:
        Variables:
          ConfigurationBucket: !Ref ConfigurationBucket
          ConfigurationKey: !Sub ${Stage}/${ConfigurationFileName}
          Stage: !Sub ${Stage}
      Description: Lambda to backup notification azure hubs
      Handler: backup.Lambda::handler
      MemorySize: 384
      Role: !GetAtt ExecutionRole.Arn
      Runtime: java8
      Timeout: 60

  BackupHourlyEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: Backs up every hour at 5 minutes past the hour
      ScheduleExpression: cron(5 * * * ? *)
      Targets:
        - Id: BackupLambda
          Arn: !GetAtt BackupLambda.Arn

  BackupHourlyEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt BackupLambda.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt BackupHourlyEvent.Arn




