AWSTemplateFormatVersion: '2010-09-09'
Description: backs up notification azure hubs
Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: mobile-notifications
  App:
    Description: Application Name
    Type: String
    Default: backup
  Stage:
    Description: Stage Name
    Type: String
    AllowedValues:
      - CODE
      - PROD
  DeployBucket:
    Description: S3 Bucket where RiffRaff uploads artifacts on Deploy
    Type: String
    Default: mobile-notifications-dist
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
        - PolicyName: invoke-lambda
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"
        - PolicyName: iam-read-and-assume
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - iam:PassRole
                - iam:GenerateCredentialReport
                - iam:Get*
                - iam:List*
              Resource: "*"
        - PolicyName: conf
          PolicyDocument:
            Statement:
            - Action: ssm:GetParametersByPath
              Effect: Allow
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/notifications/${Stage}/${Stack}

  BackupLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Stack}-${App}-${Stage}
      Code:
        S3Bucket: !Ref DeployBucket
        S3Key: !Sub ${Stack}/${Stage}/${App}/${App}.jar
      Environment:
        Variables:
          App: !Sub ${App}
          Stack: !Sub ${Stack}
          Stage: !Sub ${Stage}
      Description: Lambda to backup notification azure hubs
      Handler: backup.Lambda::handler
      MemorySize: 384
      Role: !GetAtt ExecutionRole.Arn
      Runtime: java8
      Timeout: 60

  BackupHourlyEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: Backs up twice a day
      ScheduleExpression: rate(12 hours)
      Targets:
        - Id: BackupLambda
          Arn: !GetAtt BackupLambda.Arn

  BackupHourlyEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt BackupLambda.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt BackupHourlyEvent.Arn




