AWSTemplateFormatVersion: 2010-09-09
Description: mobile-notifications-football
Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: mobile-notifications
  App:
    Description: Application name
    Type: String
    Default: football
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
    Default: CODE
  DeployBucket:
    Description: Bucket where RiffRaff uploads artifacts on deploy
    Type: String
    Default: mobile-dist
  DynamoNotificationTopic:
    Description: SNS topic to notify when there's a dynamo throttling event
    Type: String
Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Stack}-${App}-notifications-${Stage}
      AttributeDefinitions:
        - AttributeName: notificationId
          AttributeType: S
      KeySchema:
      - AttributeName: notificationId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: devx-backup-enabled
          Value: true


