package notification.models.android

object Keys {
  final val Type = "type"
  final val NotificationType = "notificationType"
  final val Debug = "debug"
  final val Title = "title"
  final val Message = "message"
  final val Ticker = "ticker"
  final val Section = "section"
  final val Keyword = "keyword"
  final val Link = "link"
  final val LinkText = "linkText"
  final val ThumbnailUrl = "thumbnailUrl"
  final val ImageUrl = "imageUrl"
  final val Edition = "edition"
  final val Editions = "editions"
  final val MapiUrl = "mapiUrl"
  final val Uri = "uri"
  final val UriType = "uriType"
  final val MatchId = "matchId"
  final val ScoringTeamName = "SCORING_TEAM_NAME"
  final val OtherTeamName = "OTHER_TEAM_NAME"
  final val ScorerName = "SCORER_NAME"
  final val GoalMins = "GOAL_MINS"
  final val HomeTeamName = "HOME_TEAM_NAME"
  final val AwayTeamName = "AWAY_TEAM_NAME"
  final val HomeTeamScore = "HOME_TEAM_SCORE"
  final val AwayTeamScore = "AWAY_TEAM_SCORE"
  final val Topics = "topics"
  final val UniqueIdentifier = "uniqueIdentifier"
  final val ElectoralCollegeSize = "electoralCollegeSize"
  final val Buzz = "buzz"
}