AWSTemplateFormatVersion: "2010-09-09"
Description: ECR repositories for MSS notification worker lambdas
Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: notificationworkerlambda-image
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              # this is the developer tools account which allows
              # teamcity to upload the images that it builds
              AWS: "arn:aws:iam::095768028460:root"
            Action:
              - "ecr:GetAuthorizationToken"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:GetRepositoryPolicy"
              - "ecr:SetRepositoryPolicy"              
              - "ecr:DescribeRepositories"
              - "ecr:ListImages"
              - "ecr:DescribeImages"
              - "ecr:BatchGetImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:PutImage"
