AWSTemplateFormatVersion: 2010-09-09
Description: A nested stack containing each of the workers which handle batched tokens with notifications to send to individual devices
Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: mobile-notifications
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
    - CODE
    - PROD
    Default: CODE
  BuildId:
    Description: Tag to be used for the image URL, e.g. riff raff build id
    Type: String
    Default: dev
  S3TemplateUrl:
    Description: Where has the nested stack's template been uploaded to
    Type: String
  DeployBucket:
    Description: Bucket where RiffRaff uploads artifacts on deploy
    Type: String
    Default: mobile-notifications-dist
  SenderTooFewInvocationsAlarmPeriod:
    Type: String
    Description: How long until no execution is suspicious, in seconds
  ReservedConcurrency:
    Type: String
    Description: How many concurrent execution to provision the lamdba with
  AlarmTopic:
    Type: String
    Description: The ARN of the SNS topic to send all the cloudwatch alarms to
  CleanerQueueArn:
    Type: String
    Description: The ARN of the cleaner SQS queue
  RunbookCopy:
    Type: String
    Default: <<<Runbook|https://docs.google.com/document/d/1aJMytnPGeWH8YLpD2_66doxqyr8dPvAVonYIOG-zmOA>>>

Resources:
  MobileNotificationsIosWorker:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        App: ios-worker
        SenderFullyQualifiedHandler: com.gu.notifications.worker.IOSSender::handleChunkTokens
        Platform: ios
        AlarmTopic: !Ref AlarmTopic
        Stack: !Ref Stack
        Stage: !Ref Stage
        BuildId: !Ref BuildId
        DeployBucket: !Ref DeployBucket
        CleanerQueueArn: !Ref CleanerQueueArn
        SenderTooFewInvocationsAlarmPeriod: !Ref SenderTooFewInvocationsAlarmPeriod
        ReservedConcurrency: !Ref ReservedConcurrency
        RunbookCopy: !Ref RunbookCopy
      TemplateURL: !Ref S3TemplateUrl

  MobileNotificationsAndroidWorker:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        App: android-worker
        SenderFullyQualifiedHandler: com.gu.notifications.worker.AndroidSender::handleChunkTokens
        Platform: android
        AlarmTopic: !Ref AlarmTopic
        Stack: !Ref Stack
        Stage: !Ref Stage
        BuildId: !Ref BuildId
        DeployBucket: !Ref DeployBucket
        CleanerQueueArn: !Ref CleanerQueueArn
        SenderTooFewInvocationsAlarmPeriod: !Ref SenderTooFewInvocationsAlarmPeriod
        ReservedConcurrency: !Ref ReservedConcurrency
        RunbookCopy: !Ref RunbookCopy
      TemplateURL: !Ref S3TemplateUrl
