AWSTemplateFormatVersion: 2010-09-09
Description: Consumes batched tokens with notifications to send to individual devices
Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: mobile-notifications
  App:
    Description: Application name
    Type: String
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
    - CODE
    - PROD
    Default: CODE
  CodeImage:
    Description: The container image URL from the ECR repository
    Type: String
    Default: 201359054765.dkr.ecr.eu-west-1.amazonaws.com/notificationworkerlambda-image
  BuildId:
    Description: Tag to be used for the image URL, e.g. riff raff build id
    Type: String
    Default: dev
  DeployBucket:
    Description: Bucket where RiffRaff uploads artifacts on deploy
    Type: String
    Default: mobile-notifications-dist
  SenderFullyQualifiedHandler:
    Description: The full name of the handler for sending notifications, including path, class name and method
    Type: String
  CleanerQueueArn:
    Type: String
    Description: The ARN of the cleaner SQS queue
  AlarmTopic:
    Type: String
    Description: The ARN of the SNS topic to send all the cloudwatch alarms to
  Platform:
    Type: String
    Description: The platform handled by this worker
    AllowedValues:
      - android
      - android-beta
      - ios
      - android-edition
      - ios-edition
  SenderTooFewInvocationsAlarmPeriod:
    Type: String
    Description: How long until no execution is suspicious, in seconds
  ReservedConcurrency:
    Type: String
    Description: How many concurrent execution to provision the lamdba with
  RunbookCopy:
    Type: String
    Default: <<<Runbook|https://docs.google.com/document/d/1aJMytnPGeWH8YLpD2_66doxqyr8dPvAVonYIOG-zmOA>>>

Conditions:
  IsProdStage: !Equals [!Ref Stage, PROD]

Resources:
  SenderDlq:
    Type: AWS::SQS::Queue
    Properties:
      Tags:
        - Key: Stage
          Value: !Ref Stage
        - Key: Stack
          Value: !Ref Stack
        - Key: App
          Value: !Ref App

  SenderSqs:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 100
      MessageRetentionPeriod: 3600 # 1 hour
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SenderDlq.Arn
        maxReceiveCount: 5
      Tags:
        - Key: Stage
          Value: !Ref Stage
        - Key: Stack
          Value: !Ref Stack
        - Key: App
          Value: !Ref App

  ExecutionRole:
    Type: AWS::IAM::Role
    DependsOn:
    - SenderSqs
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: logs
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: logs:CreateLogGroup
            Resource: !Sub "arn:aws:logs:eu-west-1:${AWS::AccountId}:*"
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource:
            - !Sub "arn:aws:logs:eu-west-1:${AWS::AccountId}:log-group:/aws/lambda/${Stack}-${App}-sender-${Stage}:*"
      - PolicyName: SQSInput
        PolicyDocument:
          Statement:
            Effect: Allow
            Action: sqs:*
            Resource:
            - !GetAtt SenderSqs.Arn
      - PolicyName: SQSOutput
        PolicyDocument:
          Statement:
            Effect: Allow
            Action: sqs:SendMessage
            Resource: !Ref CleanerQueueArn
      - PolicyName: Conf
        PolicyDocument:
          Statement:
          - Action: ssm:GetParametersByPath
            Effect: Allow
            Resource:
              !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/notifications/${Stage}/workers/${Platform}
      - PolicyName: Cloudwatch
        PolicyDocument:
          Statement:
            Effect: Allow
            Action: cloudwatch:PutMetricData
            Resource: "*"


  SenderLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Stack}-${App}-sender-${Stage}
      PackageType: Image
      Code:
        ImageUri: !Join [':', [!Ref CodeImage, !Ref BuildId]]
      ImageConfig:
        Command: [!Ref SenderFullyQualifiedHandler]
      Environment:
        Variables:
          Stage: !Ref Stage
          Stack: !Ref Stack
          App: !Ref App
          Platform: !Ref Platform
      MemorySize: 3008
      Description: Sends notifications
      Role: !GetAtt ExecutionRole.Arn
      Timeout: 90
      ReservedConcurrentExecutions: !Ref ReservedConcurrency
      Tags:
        - Key: Stage
          Value: !Ref Stage
        - Key: Stack
          Value: !Ref Stack
        - Key: App
          Value: !Ref App

  SenderSqsEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    DependsOn:
      - SenderSqs
      - SenderLambda
    Properties:
      BatchSize: 1
      Enabled: True
      EventSourceArn: !GetAtt SenderSqs.Arn
      FunctionName: !Sub ${Stack}-${App}-sender-${Stage}

  SenderThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions: [!Ref AlarmTopic]
      OKActions: [!Ref AlarmTopic]
      AlarmDescription: !Sub Triggers if the ${App} sender lambda is throttled in ${Stage}. ${RunbookCopy}
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Sub ${Stack}-${App}-sender-${Stage}
      EvaluationPeriods: 1
      MetricName: Throttles
      Namespace: AWS/Lambda
      Period: 360
      Statistic: Sum
      Threshold: 0
      TreatMissingData: notBreaching

  SenderErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions: [!Ref AlarmTopic]
      OKActions: [!Ref AlarmTopic]
      AlarmDescription: !Sub Triggers if the ${App} sender lambda errors in ${Stage}. ${RunbookCopy}
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Sub ${Stack}-${App}-sender-${Stage}
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 360
      Statistic: Sum
      Threshold: 0
      TreatMissingData: notBreaching

  SenderTooFewInvocationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions: [!Ref AlarmTopic]
      OKActions: [!Ref AlarmTopic]
      ActionsEnabled: !If [IsProdStage, true, false]
      AlarmDescription: !Sub Triggers if the ${App} senderlambda is not frequently invoked in ${Stage}. ${RunbookCopy}
      ComparisonOperator: LessThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Sub ${Stack}-${App}-sender-${Stage}
      EvaluationPeriods: 1
      MetricName: Invocations
      Namespace: AWS/Lambda
      Period: !Ref SenderTooFewInvocationsAlarmPeriod
      Statistic: Sum
      Threshold: 0
      TreatMissingData: breaching
