nodeLinker: node-modules

# Error if there are unmet peer dependency requirements
# See https://yarnpkg.com/advanced/error-codes#yn0060---incompatible_peer_dependency
# See https://yarnpkg.com/configuration/yarnrc#logFilters
logFilters:
  - code: "YN0060"
    level: "error"
